# Configuration File for GitHub Repositories
#
# This file manages settings for GitHub repositories within the Allianz organization.

# Parameters:
#   - name: Repository name. Use only lowercase letters and dashes.
#   - team name: Must be identical to the corresponding GIAM group.
repositories:

  - name: ".github"

  - name: "ospo"
    teams:
    - name: "Allianz OSPO"

  - name: "ng-aquila"
    teams:
    - name: "ng-aquila"

  - name: "calculus-prime-pnc"

  - name: "gem-config"

  - name: "license-scout"

  - name: "merge-bot"

  - name: "merge-bot-config"

  - name: "merge-processor"
