#!/usr/bin/env node

import { Octokit } from '@octokit/rest';
import yaml from 'js-yaml';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = path.join(__dirname, '..');
const defaultConfigPath = path.join(repoRoot, 'config', 'license_scan.yaml');

// ── Config ────────────────────────────────────────────────────────────────────

export async function loadConfig(configPath) {
  const raw = await readFile(configPath, 'utf8');
  const config = yaml.load(raw);
  if (!config.issue_title) {
    throw new Error(`Config missing required field: issue_title (in ${configPath})`);
  }
  if (!config['deny-licenses'] || config['deny-licenses'].length === 0) {
    throw new Error(`Config missing required field: deny-licenses (in ${configPath})`);
  }
  config.excluded_repos = config.excluded_repos ?? [];
  config.docs_link = config.docs_link ?? '';
  return config;
}

// ── Check functions ───────────────────────────────────────────────────────────

export function checkDependencyLicenses(packages, denyList) {
  const violations = [];
  for (const pkg of packages) {
    const spdxId = pkg.licenseConcluded ?? pkg.licenseDeclared ?? null;
    if (!spdxId || spdxId === 'NOASSERTION' || spdxId === 'NONE') {
      continue;
    }
    if (denyList.includes(spdxId)) {
      violations.push({
        name: pkg.name ?? '',
        version: pkg.versionInfo ?? '',
        spdxId,
      });
    }
  }
  return violations;
}

// ── SBOM fetching (async API) ─────────────────────────────────────────────────

// Returns packages array from the SBOM, or null if unavailable (403/404).
export async function fetchSbomPackages(octokit, org, repo, token) {
  let reportUrl;
  try {
    const { data } = await octokit.request('GET /repos/{owner}/{repo}/dependency-graph/sbom/generate-report', {
      owner: org,
      repo,
      headers: { 'X-GitHub-Api-Version': '2026-03-10' },
    });
    reportUrl = data?.sbom_url;
  } catch (err) {
    if (err.status === 404 || err.status === 403) return null;
    throw err;
  }

  if (!reportUrl) return [];

  const authHeaders = {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2026-03-10',
  };

  // Poll until the report is ready (202 → still processing, 302 → redirect to download)
  for (let attempt = 0; attempt < 30; attempt++) {
    const res = await fetch(reportUrl, { headers: authHeaders, redirect: 'manual' });
    if (res.status === 302) {
      const downloadUrl = res.headers.get('location');
      const download = await fetch(downloadUrl);
      const sbom = await download.json();
      return sbom?.packages ?? sbom?.sbom?.packages ?? [];
    }
    if (res.status === 200) {
      const sbom = await res.json();
      return sbom?.packages ?? sbom?.sbom?.packages ?? [];
    }
    if (res.status === 202) {
      await new Promise(r => setTimeout(r, 2000));
      continue;
    }
    if (res.status === 404 || res.status === 403) return null;
    throw new Error(`Unexpected status ${res.status} polling SBOM for ${repo}`);
  }
  throw new Error(`SBOM generation timed out for ${repo}`);
}

// ── Issue body ────────────────────────────────────────────────────────────────

export function buildIssueBody(violations, config) {
  const rows = violations.map(({ name, version, spdxId }) =>
    `| ${name} | ${version} | ${spdxId} |`
  );
  const policyLine = config.docs_link
    ? `Please review the [License Policy](${config.docs_link}) and replace or remove the dependencies above.`
    : 'Please replace or remove the dependencies above.';
  return [
    '## Dependency License Violation',
    '',
    'The following dependencies use licenses that are not permitted:',
    '',
    '| Package | Version | License |',
    '|---------|---------|---------|',
    ...rows,
    '',
    policyLine,
    '',
    '_This issue was automatically generated by the OSPO license scanner._',
  ].join('\n');
}

// ── Issue helpers ─────────────────────────────────────────────────────────────

export async function findOpenIssue(octokit, org, repo, issueTitle) {
  const issues = await octokit.paginate(octokit.rest.issues.listForRepo, {
    owner: org,
    repo,
    state: 'open',
  });
  const found = issues.find(i => i.title === issueTitle && !i.pull_request);
  return found ? found.number : null;
}

async function createIssue(octokit, org, repo, title, body) {
  await octokit.rest.issues.create({ owner: org, repo, title, body });
}

async function updateIssue(octokit, org, repo, issueNumber, body) {
  await octokit.rest.issues.update({ owner: org, repo, issue_number: issueNumber, body });
}

async function closeIssue(octokit, org, repo, issueNumber) {
  await octokit.rest.issues.createComment({
    owner: org,
    repo,
    issue_number: issueNumber,
    body: '_All dependency license violations have been resolved. Closing this issue automatically._',
  });
  await octokit.rest.issues.update({
    owner: org,
    repo,
    issue_number: issueNumber,
    state: 'closed',
  });
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2);
  let org = null;
  let configPath = defaultConfigPath;
  let dryRun = false;
  let debug = false;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--org':
        org = args[++i];
        break;
      case '--config':
        configPath = path.resolve(args[++i]);
        break;
      case '--dry-run':
        dryRun = true;
        break;
      case '--debug':
        debug = true;
        break;
    }
  }

  if (!org) {
    console.error('Error: --org is required');
    process.exit(1);
  }

  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (!token) {
    console.error('Error: GITHUB_TOKEN (or GH_TOKEN) environment variable is not set');
    process.exit(1);
  }

  const config = await loadConfig(configPath);
  const octokit = new Octokit({ auth: token });

  const allRepos = await octokit.paginate(octokit.rest.repos.listForOrg, {
    org,
    type: 'all',
    per_page: 100,
  });

  const excluded = [];
  const archived = [];
  const active = [];

  for (const repo of allRepos) {
    if (config.excluded_repos.includes(repo.name)) {
      excluded.push(repo);
    } else if (repo.archived) {
      archived.push(repo);
    } else {
      active.push(repo);
    }
  }

  console.log('Results');
  console.log('───────');

  const pendingCreates = [];
  const pendingUpdates = [];
  const pendingCloses = [];
  const skippedUnavailable = [];

  for (const repo of active) {
    if (debug) console.log(`  Fetching SBOM for ${repo.name}...`);
    const sbomPackages = await fetchSbomPackages(octokit, org, repo.name, token);
    if (sbomPackages === null) {
      skippedUnavailable.push(repo.name);
      continue;
    }

    const violations = checkDependencyLicenses(sbomPackages, config['deny-licenses']);

    if (violations.length > 0) {
      // Group by license for the summary line
      const byLicense = {};
      for (const v of violations) {
        if (!byLicense[v.spdxId]) byLicense[v.spdxId] = [];
        byLicense[v.spdxId].push(v.name);
      }
      const summary = Object.entries(byLicense)
        .map(([lic, names]) => `${lic} (${names[0]})`)
        .join(', ');
      console.log(`❌ ${repo.name}  [${summary}]`);
      for (const v of violations) {
        console.log(`     ${v.spdxId}: ${v.name}@${v.version}`);
      }

      const existingIssue = await findOpenIssue(octokit, org, repo.name, config.issue_title);
      const body = buildIssueBody(violations, config);
      if (!existingIssue) {
        if (dryRun) {
          pendingCreates.push(repo.name);
        } else {
          await createIssue(octokit, org, repo.name, config.issue_title, body);
        }
      } else {
        if (dryRun) {
          pendingUpdates.push({ number: existingIssue, name: repo.name });
        } else {
          await updateIssue(octokit, org, repo.name, existingIssue, body);
        }
      }
    } else {
      console.log(`✅ ${repo.name}`);
      const existingIssue = await findOpenIssue(octokit, org, repo.name, config.issue_title);
      if (existingIssue) {
        if (dryRun) {
          pendingCloses.push({ number: existingIssue, name: repo.name });
        } else {
          await closeIssue(octokit, org, repo.name, existingIssue);
        }
      }
    }
  }

  if (archived.length > 0) {
    console.log('');
    console.log('Skipped (archived)');
    console.log('──────────────────');
    for (const repo of archived) {
      console.log(`– ${repo.name}`);
    }
  }

  if (skippedUnavailable.length > 0) {
    console.log('');
    console.log('Skipped (dependency graph unavailable)');
    console.log('───────────────────────────────────────');
    for (const name of skippedUnavailable) {
      console.log(`– ${name}`);
    }
  }

  if (excluded.length > 0) {
    console.log('');
    console.log('Skipped (configuration)');
    console.log('───────────────────────');
    for (const repo of excluded) {
      console.log(`– ${repo.name}`);
    }
  }

  if (dryRun && (pendingCreates.length > 0 || pendingUpdates.length > 0 || pendingCloses.length > 0)) {
    console.log('');
    console.log(`──── Dry-run: ${pendingCreates.length} issue would be created, ${pendingUpdates.length} would be updated, ${pendingCloses.length} would be closed ────`);
    for (const name of pendingCreates) {
      console.log(`  ✉️   create  ${name}`);
    }
    for (const { number, name } of pendingUpdates) {
      console.log(`  ✏️   update  #${number}  ${name}`);
    }
    for (const { number, name } of pendingCloses) {
      console.log(`  ✔️   close   #${number}  ${name}`);
    }
  }

  process.exit(0);
}

// Only run main() when this file is the entry point (not when imported by tests)
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(err => {
    console.error('Fatal error:', err.message);
    process.exit(1);
  });
}
