#!/usr/bin/env node

import { Octokit } from '@octokit/rest';
import simpleGit from 'simple-git';
import yaml from 'js-yaml';
import { readFile, readdir, access } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = path.join(__dirname, '..');
const lintCacheDir = path.join(repoRoot, 'lint_cache');
const defaultConfigPath = path.join(repoRoot, 'config', 'lint_repos.yaml');

// ── Config ────────────────────────────────────────────────────────────────────

export async function loadConfig(configPath) {
  const raw = await readFile(configPath, 'utf8');
  const config = yaml.load(raw);
  if (!config.issue_title) {
    throw new Error(`Config missing required field: issue_title (in ${configPath})`);
  }
  config.allowed_topics = config.allowed_topics ?? [];
  config.excluded_repos = config.excluded_repos ?? [];
  return config;
}

// ── Check functions ───────────────────────────────────────────────────────────

export function checkDescription(repo) {
  if (repo.description && repo.description.trim().length > 0) {
    return { passed: true };
  }
  return { passed: false, detail: 'No description set' };
}

export function checkTopics(repo, allowedTopics) {
  const topics = repo.topics ?? [];
  if (topics.length === 0) {
    return { passed: false, detail: 'No topics set' };
  }
  if (topics.length > 5) {
    return { passed: false, detail: `Too many topics (${topics.length}); maximum is 5` };
  }
  if (allowedTopics.length > 0) {
    const invalid = topics.filter(t => !allowedTopics.includes(t));
    if (invalid.length > 0) {
      return { passed: false, detail: `Invalid topic(s): ${invalid.join(', ')}` };
    }
  }
  return { passed: true };
}

export function checkLicense(repo, allowedLicenses) {
  const spdxId = repo.license?.spdx_id ?? null;
  if (spdxId === null) {
    return { passed: false, detail: 'No license detected' };
  }
  if (spdxId === 'NOASSERTION') {
    return {
      passed: false,
      detail: 'Custom license text detected — GitHub could not identify a standard SPDX license. Ensure the license is based on an approved one.',
    };
  }
  if (!allowedLicenses.includes(spdxId)) {
    return { passed: false, detail: `'${spdxId}' is not in the approved list` };
  }
  return { passed: true };
}

export async function checkRequiredFile(cloneDir, fileSpec) {
  const { pattern, search_paths } = fileSpec;
  const searchPaths = search_paths ?? ['.'];
  // Patterns are always prefix globs (README*, CONTRIBUTING*, LICENSE*) — match case-insensitively
  const prefix = pattern.replace(/\*.*$/, '').toUpperCase();
  for (const searchPath of searchPaths) {
    const dir = path.join(cloneDir, searchPath);
    try {
      const entries = await readdir(dir);
      const match = entries.find(f => f.toUpperCase().startsWith(prefix));
      if (match) return { passed: true };
    } catch {
      // Directory doesn't exist — try next path
    }
  }
  return { passed: false, detail: `File not found in ${searchPaths.join(', ')}` };
}

// ── Issue body ────────────────────────────────────────────────────────────────

export function buildIssueBody(allChecks, docsLink) {
  const rows = allChecks.map(({ checkName, passed, detail }) => {
    const icon = passed ? '✅' : '❌';
    const status = passed ? 'Passed' : 'Failed';
    const detailCell = passed ? '' : (detail ?? '');
    return `| ${checkName} | ${icon} ${status} | ${detailCell} |`;
  });
  return [
    '## Mandatory Repository Configuration',
    '',
    'The following compliance checks failed for this repository:',
    '',
    '| Check | Status | Details |',
    '|-------|--------|---------|',
    ...rows,
    '',
    `Please review the [standards and compliance guide](${docsLink}) and address the issues above.`,
    '',
    '_This issue was automatically generated by the OSPO linting bot._',
  ].join('\n');
}

// ── Issue helpers ─────────────────────────────────────────────────────────────

async function findOpenIssue(octokit, org, repo, issueTitle) {
  const issues = await octokit.paginate(octokit.rest.issues.listForRepo, {
    owner: org,
    repo,
    state: 'open',
  });
  const found = issues.find(i => i.title === issueTitle);
  return found ? found.number : null;
}

async function createIssue(octokit, org, repo, title, body) {
  await octokit.rest.issues.create({ owner: org, repo, title, body });
}

async function closeIssue(octokit, org, repo, issueNumber) {
  await octokit.rest.issues.createComment({
    owner: org,
    repo,
    issue_number: issueNumber,
    body: '_All compliance checks now pass. Closing this issue automatically._',
  });
  await octokit.rest.issues.update({
    owner: org,
    repo,
    issue_number: issueNumber,
    state: 'closed',
  });
}

// ── Cloning ───────────────────────────────────────────────────────────────────

async function cloneOrUpdate(repoName, cloneDir, org, debug) {
  const url = `https://github.com/${org}/${repoName}.git`;
  let exists = false;
  try {
    await access(cloneDir);
    exists = true;
  } catch {
    /* doesn't exist */
  }
  if (debug) {
    console.log(`  ${exists ? 'Updating' : 'Cloning'} ${repoName}...`);
  }
  if (exists) {
    const git = simpleGit(cloneDir);
    await git.fetch(['--depth', '1']);
    await git.reset(['--hard', 'FETCH_HEAD']);
  } else {
    await simpleGit().clone(url, cloneDir, ['--depth', '1']);
  }
}

async function cloneBatch(batch, cacheDir, org, debug) {
  await Promise.all(
    batch.map(repo => cloneOrUpdate(repo.name, path.join(cacheDir, repo.name), org, debug))
  );
}

// ── Output helpers ────────────────────────────────────────────────────────────

function formatResultLine(repoName, failures, isArchived) {
  const passIcon = isArchived ? '✔️' : '✅';
  const failIcon = isArchived ? '✖️' : '❌';
  if (failures.length === 0) {
    return `${passIcon} ${repoName}`;
  }
  const names = failures.map(f => f.checkName).join(', ');
  return `${failIcon} ${repoName}  [${names}]`;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2);
  let org = null;
  let configPath = defaultConfigPath;
  let dryRun = false;
  let debug = false;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--org':
        org = args[++i];
        break;
      case '--config':
        configPath = path.resolve(args[++i]);
        break;
      case '--dry-run':
        dryRun = true;
        break;
      case '--debug':
        debug = true;
        break;
    }
  }

  if (!org) {
    console.error('Error: --org is required');
    process.exit(1);
  }

  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
  if (!token) {
    console.error('Error: GITHUB_TOKEN (or GH_TOKEN) environment variable is not set');
    process.exit(1);
  }

  const config = await loadConfig(configPath);
  const octokit = new Octokit({ auth: token });

  const allRepos = await octokit.paginate(octokit.rest.repos.listForOrg, {
    org,
    type: 'public',
    per_page: 100,
  });

  const excluded = [];
  const archived = [];
  const active = [];

  for (const repo of allRepos) {
    if (config.excluded_repos.includes(repo.name)) {
      excluded.push(repo);
    } else if (repo.archived) {
      archived.push(repo);
    } else {
      active.push(repo);
    }
  }

  // Clone active repos in batches of 5
  const batchCount = Math.ceil(active.length / 5);
  for (let i = 0; i < active.length; i += 5) {
    const batch = active.slice(i, i + 5);
    const batchNum = Math.floor(i / 5) + 1;
    if (debug) console.log(`Cloning batch ${batchNum}/${batchCount}...`);
    await cloneBatch(batch, lintCacheDir, org, debug);
  }
  if (debug && active.length > 0) console.log('');

  console.log('Results');
  console.log('───────');

  let anyFailed = false;
  const pendingCreates = [];
  const pendingCloses = [];

  for (const repo of active) {
    const cloneDir = path.join(lintCacheDir, repo.name);
    const allChecks = [];

    allChecks.push({ checkName: 'Repository Description', ...checkDescription(repo) });
    allChecks.push({ checkName: 'Repository Topics', ...checkTopics(repo, config.allowed_topics) });
    allChecks.push({ checkName: 'License Type', ...checkLicense(repo, config.allowed_licenses ?? []) });

    for (const fileSpec of config.required_files ?? []) {
      const result = await checkRequiredFile(cloneDir, fileSpec);
      allChecks.push({ checkName: fileSpec.description ?? fileSpec.pattern, ...result });
    }

    const failures = allChecks.filter(c => !c.passed);

    if (failures.length > 0) {
      anyFailed = true;
      console.log(formatResultLine(repo.name, failures, false));
      if (debug) {
        for (const f of failures) {
          console.log(`     ${f.checkName}: ${f.detail}`);
        }
      }
      const existingIssue = await findOpenIssue(octokit, org, repo.name, config.issue_title);
      if (!existingIssue) {
        if (dryRun) {
          pendingCreates.push(repo.name);
        } else {
          const body = buildIssueBody(allChecks, config.docs_link);
          await createIssue(octokit, org, repo.name, config.issue_title, body);
        }
      }
    } else {
      console.log(formatResultLine(repo.name, [], false));
      const existingIssue = await findOpenIssue(octokit, org, repo.name, config.issue_title);
      if (existingIssue) {
        if (dryRun) {
          pendingCloses.push({ number: existingIssue, name: repo.name });
        } else {
          await closeIssue(octokit, org, repo.name, existingIssue);
        }
      }
    }
  }

  if (archived.length > 0) {
    console.log('');
    console.log('Skipped (archived)');
    console.log('──────────────────');
    for (const repo of archived) {
      const allChecks = [];
      allChecks.push({ checkName: 'Repository Description', ...checkDescription(repo) });
      allChecks.push({ checkName: 'Repository Topics', ...checkTopics(repo, config.allowed_topics) });
      allChecks.push({ checkName: 'License Type', ...checkLicense(repo, config.allowed_licenses ?? []) });
      const failures = allChecks.filter(c => !c.passed);
      console.log(formatResultLine(repo.name, failures, true));
    }
  }

  if (excluded.length > 0) {
    console.log('');
    console.log('Skipped (configuration)');
    console.log('───────────────────────');
    for (const repo of excluded) {
      console.log(`– ${repo.name}`);
    }
  }

  if (dryRun && (pendingCreates.length > 0 || pendingCloses.length > 0)) {
    const createWord = pendingCreates.length !== 1 ? 'issues' : 'issue';
    console.log('');
    console.log(`──── Dry-run: ${pendingCreates.length} ${createWord} would be created, ${pendingCloses.length} would be closed ────`);
    for (const name of pendingCreates) {
      console.log(`  ✉️   create  ${name}`);
    }
    for (const { number, name } of pendingCloses) {
      console.log(`  ✔️   close  #${number}  ${name}`);
    }
  }

  process.exit(anyFailed ? 1 : 0);
}

// Only run main() when this file is the entry point (not when imported by tests)
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(err => {
    console.error('Fatal error:', err.message);
    process.exit(1);
  });
}
