test_archive_repos:
	../archive_repos.sh --org ospo-sandbox --config ./test/archive_repos.yaml --debug

test_lint_repos:
	cd ../.. && node scripts/lint_repos.js --org ospo-sandbox --config scripts/test/lint_repos.yaml --debug

test_create_repos:
	../create_repos.sh --org ospo-sandbox --config ./test/create_repos.yaml --debug