test_archive_repos:
	../archive_repos.sh --org ospo-sandbox --config ./test/archive_repos.yaml --debug

test_lint_repos:
	../lint_repos.sh --org ospo-sandbox --config ./test/lint_repos.yaml --debug

test_create_repos:
	../create_repos.sh --org ospo-sandbox --config ./test/create_repos.yaml --debug